// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID        int64
	PostID    int64
	UserID    int64
	Content   sql.NullString
	CreatedAt time.Time
}

type Follower struct {
	UserID     int64
	FollowerID int64
	CreatedAt  time.Time
}

type Post struct {
	ID        int64
	Title     string
	UserID    int64
	Content   string
	CreatedAt time.Time
	Tags      []string
	UpdatedAt time.Time
	Version   sql.NullInt32
}

type Role struct {
	ID          int64
	Name        string
	Level       int32
	Description sql.NullString
}

type User struct {
	ID        int64
	Email     string
	Username  string
	Password  []byte
	CreatedAt time.Time
	IsActive  bool
	RoleID    int32
}

type UserInvitation struct {
	Token  []byte
	UserID int64
	Expiry time.Time
}
