with-expecter: true
filename: "mock_{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
inpackage: True
packages:
  github.com/sergdort/Social/internal/store/cache:
    interfaces:
      UsersCache:
  github.com/sergdort/Social/internal/auth:
    interfaces:
      Authenticator:
  github.com/sergdort/Social/internal/store:
    interfaces:
      PostsRepository:
      UsersRepository:
      CommentsRepository:
      FollowsRepository:
      RolesRepository: