with-expecter: true
filename: "mock_{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
inpackage: True
packages:
  github.com/sergdort/Social/internal/auth:
    interfaces:
      Authenticator:
  github.com/sergdort/Social/business/domain:
    interfaces:
      UsersCache:
      UsersRepository:
      RolesRepository:
      CommentsRepository:
      PostsRepository:
      FollowsRepository:
  github.com/sergdort/Social/internal/store/sqlc:
    interfaces:
      DBTX:
